from fastapi import APIRouter, status, Security, HTTPException
from fastapi.security import HTTPAuthorizationCredentials
from pydantic import BaseModel
from bson import ObjectId
from typing import Optional

from database import get_db
from services.jwt_auth import verify_and_decode_token, security

router = APIRouter()

class DashboardStatsResponse(BaseModel):
    files_uploaded: int
    transcripts: int
    summaries: int
    action_items: int
    total_files: Optional[int] = None
    total_transcripts: Optional[int] = None
    total_summaries: Optional[int] = None
    total_action_items: Optional[int] = None
    heading: str = "My Meeting Analytics"
    status: str = "ok"
    user_id: Optional[str] = None
    live_database_statistics: bool = True

def compute_user_stats(current_user_id: str) -> dict:
    """
    Computes real-time live MongoDB collection statistics scoped strictly to the authenticated user ID.
    Queries:
      files.count_documents({"user_id": current_user_id})
      transcripts.count_documents({"user_id": current_user_id})
      summaries.count_documents({"user_id": current_user_id})
      action_items.count_documents({"user_id": current_user_id})
    """
    db = get_db()
    
    user_id_str = str(current_user_id).strip()
    user_match = {
        "$or": [
            {"user_id": user_id_str},
            {"user_id": ObjectId(user_id_str)} if ObjectId.is_valid(user_id_str) else {"user_id": user_id_str}
        ]
    }
    
    # 1. Total files uploaded by this user (PDFs and Audio files in 'files')
    files_uploaded = db["files"].count_documents(user_match)
    docs_count = db["documents"].count_documents(user_match)
    # Ensure any document in documents is also accounted for
    files_uploaded = max(files_uploaded, docs_count)
    
    # 2. Transcripts generated by this user
    transcripts_count = db["transcripts"].count_documents(user_match)
    
    # 3. Summaries generated by this user
    summaries_count = db["summaries"].count_documents(user_match)
    
    # 4. Action items generated by this user
    # Check single-task action items
    single_tasks_count = db["action_items"].count_documents({
        **user_match,
        "task": {"$exists": True, "$ne": None}
    })
    # Check container action items
    container_docs = list(db["action_items"].find({
        **user_match,
        "tasks": {"$exists": True, "$ne": []}
    }))
    
    if single_tasks_count > 0 and not container_docs:
        action_items_count = single_tasks_count
    elif container_docs and single_tasks_count == 0:
        action_items_count = sum(len(c.get("tasks", [])) for c in container_docs if isinstance(c.get("tasks"), list))
    elif single_tasks_count > 0 and container_docs:
        action_items_count = single_tasks_count
    else:
        action_items_count = db["action_items"].count_documents(user_match)

    return {
        "files_uploaded": files_uploaded,
        "transcripts": transcripts_count,
        "summaries": summaries_count,
        "action_items": action_items_count,
        "total_files": files_uploaded,
        "total_transcripts": transcripts_count,
        "total_summaries": summaries_count,
        "total_action_items": action_items_count,
        "heading": "My Meeting Analytics",
        "status": "ok",
        "user_id": user_id_str,
        "live_database_statistics": True
    }

@router.get(
    "/stats",
    response_model=DashboardStatsResponse,
    status_code=status.HTTP_200_OK,
    summary="Get user-specific dashboard statistics strictly scoped to the logged-in user"
)
def get_dashboard_stats(
    credentials: Optional[HTTPAuthorizationCredentials] = Security(security)
):
    if not credentials or not credentials.credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required. Please provide a valid Bearer JWT token in the Authorization header.",
            headers={"WWW-Authenticate": "Bearer"}
        )
    try:
        payload = verify_and_decode_token(credentials.credentials)
        user_id = payload.get("user_id") or payload.get("sub")
        if not user_id:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token: user_id missing from payload",
                headers={"WWW-Authenticate": "Bearer"}
            )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid token: {str(e)}",
            headers={"WWW-Authenticate": "Bearer"}
        )

    return compute_user_stats(str(user_id))
